Foundant.ImageStore.Web/Pages/Album/Image/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using static Foundant.AddImageTag;
using static Foundant.GetImageById;
using static Foundant.ImageStore.Web.Feature.Image.UpdateImage;

namespace Foundant.ImageStore.Web.Pages.Album.Image
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        [BindProperty]
        public ImageEditDTO ImageToEdit { get; set; }

        public IndexModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync(Guid albumId, Guid imageId)
        {
            var image = await _mediator.Send(new GetImageByIdQuery(albumId, imageId));
            ImageToEdit = new ImageEditDTO { AlbumId = albumId, ImageId = imageId, ImageDescription = image.Description, ImageName = image.Name, Tags = image.Tags, Extension = image.Extension };
            AddTag = new AddTagDTO { AlbumId = albumId, ImageId = imageId };
        }

        public async Task<IActionResult> OnPostAsync(ImageEditDTO imageToEdit)
        {
            _ = await _mediator.Send(new UpdateImageCommand(imageToEdit.AlbumId, imageToEdit.ImageId, imageToEdit.ImageName, imageToEdit.ImageDescription));

            return RedirectToPage("/Album/Image/Index", new { albumId = imageToEdit.AlbumId, imageId = imageToEdit.ImageId });
        }

        public class ImageEditDTO
        {
            public Guid AlbumId { get; set; }
            public Guid ImageId { get; set; }
            public string ImageName { get; set; }
            public string ImageDescription { get; set; }
            public List<string> Tags { get; set; }
            public string Extension { get; set; }
        }

        [BindProperty]
        public AddTagDTO AddTag { get; set; }

        public async Task<IActionResult> OnPostAddTagAsync(AddTagDTO tagDetails )
        {
            _ = await _mediator.Send(new AddImageTagCommand(tagDetails.AlbumId, tagDetails.ImageId, tagDetails.Tag));

            return RedirectToPage("/Album/Image/Index", new { albumId = tagDetails.AlbumId, imageId = tagDetails.ImageId });
        }

        [BindProperty]
        public Guid AlbumId { get; set; }

        [BindProperty]
        public Guid ImageId { get; set; }

        [BindProperty]
        public string Tag { get; set; }

        public class AddTagDTO
        {
            public Guid AlbumId { get; set; }
            public Guid ImageId { get; set; }
            public string Tag { get; set; }
        }
    }
}

Foundant.ImageStore.Web/Pages/Image/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using static Foundant.AddImageTag;
using static Foundant.GetImageById;
using static Foundant.ImageStore.Web.Feature.Image.UpdateImage;

namespace Foundant.ImageStore.Web.Pages.Image
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        [BindProperty]
        public ImageEditDTO ImageToEdit { get; set; }

        public IndexModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync(Guid albumId, Guid imageId)
        {
            var image = await _mediator.Send(new GetImageByIdQuery(albumId, imageId));
            ImageToEdit = new ImageEditDTO { AlbumId = albumId, ImageId = imageId, ImageDescription = image.Description, ImageName = image.Name, Tags = image.Tags, Extension = image.Extension };
            AddTag = new AddTagDTO { AlbumId = albumId, ImageId = imageId };
        }

        public async Task<IActionResult> OnPostAsync(ImageEditDTO imageToEdit)
        {
            _ = await _mediator.Send(new UpdateImageCommand(imageToEdit.AlbumId, imageToEdit.ImageId, imageToEdit.ImageName, imageToEdit.ImageDescription));

            return RedirectToPage("/Image/Index", new { albumId = imageToEdit.AlbumId, imageId = imageToEdit.ImageId });
        }

        public class ImageEditDTO
        {
            public Guid AlbumId { get; set; }
            public Guid ImageId { get; set; }
            public string ImageName { get; set; }
            public string ImageDescription { get; set; }
            public List<string> Tags { get; set; }
            public string Extension { get; set; }
        }

        [BindProperty]
        public AddTagDTO AddTag { get; set; }

        public async Task<IActionResult> OnPostAddTagAsync(AddTagDTO tagDetails )
        {
            _ = await _mediator.Send(new AddImageTagCommand(tagDetails.AlbumId, tagDetails.ImageId, tagDetails.Tag));

            return RedirectToPage("/Image/Index", new { albumId = tagDetails.AlbumId, imageId = tagDetails.ImageId });
        }

        [BindProperty]
        public Guid AlbumId { get; set; }

        [BindProperty]
        public Guid ImageId { get; set; }

        [BindProperty]
        public string Tag { get; set; }

        public class AddTagDTO
        {
            public Guid AlbumId { get; set; }
            public Guid ImageId { get; set; }
            public string Tag { get; set; }
        }
    }
}

Foundant.ImageStore.Web/Pages/Image/Index.cshtml
@page "{albumId:Guid}/{imageId:Guid}"
@model Foundant.ImageStore.Web.Pages.Image.IndexModel
@{
}

<a asp-page="/Album" asp-route-id="AlbumId"><< Back to Album</a>
<div style="display: flex; flex-direction: column; margin-left: auto; margin-right: auto; margin-top: 2rem;">
    <div style="display: flex; flex-direction: row;">
        <div style="width: 33%; text-align: right;">
            <div style="display: flex; flex-direction: column">
                <div>
                    <img style="border: 1px solid #e2e2e2; border-radius: .75rem" src="~/albums/@Model.ImageToEdit.AlbumId/@Model.ImageToEdit.ImageId@Model.ImageToEdit.Extension" alt="@Model.ImageToEdit.ImageName" />
                </div>
                <span>
                    @{ 
                        string imageUrl = $"https://{Request.Host}/albums/{Model.ImageToEdit.AlbumId}/{Model.ImageToEdit.ImageId}{Model.ImageToEdit.Extension}";
                    }
                    <a href="@imageUrl" target="_blank">@imageUrl</a>
                    
                </span>
            </div>
            
        </div>
        <div style="width: 66%; text-align: left;">
            <form method="post" style="width: 100%;">
                <input asp-for="ImageToEdit.AlbumId" type="hidden" />
                <input asp-for="ImageToEdit.ImageId" type="hidden" />
                <div class="formGroup">
                    <div style="width: 20%">
                        <label asp-for="ImageToEdit.ImageName" class="formGroupLabel">Name:</label>
                    </div>
                    <div style="width: 80%">
                        <input asp-for="ImageToEdit.ImageName" class="formGroupField" />
                    </div>
                </div>
                <div class="formGroup">
                    <div style="width: 20%">
                        <label asp-for="ImageToEdit.ImageDescription" class="formGroupLabel">Description:</label>
                    </div>
                    <div style="width: 80%">
                        <input asp-for="ImageToEdit.ImageDescription" class="formGroupField" />
                    </div>
                </div>
                <div class="formGroup">
                    <div style="width: 20%"></div>
                    <div style="width: 80%">
                        <button type="submit" class="formButton">Update</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div style="display: flex; flex-direction: row; justify-content: center">
        <div style="width: 33%"></div>
        <div style="width: 66%;">

            <form method="post" asp-page-handler="AddTag" style="width: 100%; margin-bottom: 2rem;">
                <input asp-for="AlbumId" type="hidden" />
                <input asp-for="ImageId" type="hidden" />
                <div class="formGroup">
                    <div style="width: 20%">
                        <label asp-for="Tag" class="formGroupLabel">Tag:</label>
                    </div>
                    <div style="width: 80%">
                        <input asp-for="Tag" class="formGroupField" placeholder="Add a tag" />
                    </div>
                </div>
                <div class="formGroup">
                    <div style="width: 20%"></div>
                    <div style="width: 80%">
                        <button type="submit" class="formButton">Update</button>
                    </div>
                </div>
            </form>
            <div>
                <div style="width: 33%"></div>
                <div style="width: 66%">
                    <div class="formGroup">
                        <div style="width: 30%"></div>
                        <div style="width: 70%">
                            @if (Model.ImageToEdit.Tags != null && Model.ImageToEdit.Tags.Count() > 0)
                            {
                                @foreach (var tag in Model.ImageToEdit.Tags)
                                {
                                    <span class="tagItem">
                                        @tag
                                    </span>
                                }
                            }
                            else
                            {
                                <span>No tags assigned</span>
                            }
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
    </div>
</div>