Foundant.ImageStore.Web/Pages/Album/Image/Index.cshtml.cs
using MediatR;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using static Foundant.AddImageTag;
using static Foundant.GetImageById;
using static Foundant.ImageStore.Web.Feature.Image.UpdateImage;

namespace Foundant.ImageStore.Web.Pages.Album.Image
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        [BindProperty]
        public ImageEditDTO ImageToEdit { get; set; }

        public IndexModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync(Guid albumId, Guid imageId)
        {
            var image = await _mediator.Send(new GetImageByIdQuery(albumId, imageId));
            ImageToEdit = new ImageEditDTO { AlbumId = albumId, ImageId = imageId, ImageDescription = image.Description, ImageName = image.Name, Tags = image.Tags, Extension = image.Extension };
            AddTag = new AddTagDTO { AlbumId = albumId, ImageId = imageId };
        }

        public async Task<IActionResult> OnPostAsync(ImageEditDTO imageToEdit)
        {
            _ = await _mediator.Send(new UpdateImageCommand(imageToEdit.AlbumId, imageToEdit.ImageId, imageToEdit.ImageName, imageToEdit.ImageDescription));

            return RedirectToPage("/Album/Image/Index", new { albumId = imageToEdit.AlbumId, imageId = imageToEdit.ImageId });
        }

        public class ImageEditDTO
        {
            public Guid AlbumId { get; set; }
            public Guid ImageId { get; set; }
            public string ImageName { get; set; }
            public string ImageDescription { get; set; }
            public List<string> Tags { get; set; }
            public string Extension { get; set; }
        }

        [BindProperty]
        public AddTagDTO AddTag { get; set; }

        public async Task<IActionResult> OnPostAddTagAsync(AddTagDTO tagDetails )
        {
            _ = await _mediator.Send(new AddImageTagCommand(tagDetails.AlbumId, tagDetails.ImageId, tagDetails.Tag));

            return RedirectToPage("/Album/Image/Index", new { albumId = tagDetails.AlbumId, imageId = tagDetails.ImageId });
        }

        [BindProperty]
        public Guid AlbumId { get; set; }

        [BindProperty]
        public Guid ImageId { get; set; }

        [BindProperty]
        public string Tag { get; set; }

        public class AddTagDTO
        {
            public Guid AlbumId { get; set; }
            public Guid ImageId { get; set; }
            public string Tag { get; set; }
        }
    }
}

Foundant.ImageStore.Web/Pages/Album/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MediatR;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using static Foundant.AddImage;
using static Foundant.GetAlbumById;
using static Foundant.ImageStore.Web.Feature.Image.GetImageTags;
using static Foundant.RemoveImageFromAlbumById;

namespace Foundant.ImageStore.Web.Pages.Album
{
    public class IndexModel : PageModel
    {
        private readonly IMediator _mediator;
        public AlbumDTO AlbumDetails { get; private set; }
        public List<string> Tags { get; private set; }
        public string TagToSearch { get; private set; }
        [BindProperty]
        public Guid AlbumId { get; private set; }

        public IndexModel(IMediator mediator)
        {
            _mediator = mediator;
        }

        public async Task OnGetAsync(Guid id)
        {
            AlbumId = id;
            var album = await _mediator.Send(new GetAlbumByIdQuery(id));
            AlbumDetails = new AlbumDTO
            {
                Id = album.Id,
                Name = album.Name,
                Images = album.Images?.Select(c => new ImageDTO { Id = c.Id, Name = c.Name, Created = c.Created, Extension = c.Extension }).ToList()
            };

            Data = new AddImageCommand(id, string.Empty, null);

            Tags = await _mediator.Send(new GetImageTagsQuery());
        }

        public async Task OnPostSearchByTagAsync(Guid albumId, string tagToSearch)
        {
            AlbumId = albumId;
            var album = await _mediator.Send(new GetAlbumByIdQuery(albumId));
            AlbumDetails = new AlbumDTO
            {
                Id = album.Id,
                Name = album.Name
            };

            AlbumDetails.Images = album.Images?.Where(c => c.Tags.Contains(tagToSearch)).Select(c => new ImageDTO { Id = c.Id, Name = c.Name, Created = c.Created, Extension = c.Extension }).ToList();

            Data = new AddImageCommand(albumId, string.Empty, null);
            Tags = await _mediator.Send(new GetImageTagsQuery());

        }

        public async Task<IActionResult> OnGetDeleteImageAsync(Guid albumId, Guid imageId)
        {
            var album = await _mediator.Send(new RemoveImageFromAlbumByIdCommand(albumId, imageId));

            return RedirectToPage("/Album/Index", new { id = albumId });
        }

        [BindProperty]
        public AddImageCommand Data { get; set; }

        public async Task<IActionResult> OnPostAsync()
        {
            // TODO: validate mime type

            var value = await _mediator.Send(Data);

            return RedirectToPage("/Album/Index", new { id = Data.AlbumId });
        }

        public class AlbumDTO
        {
            public Guid Id { get; set; }
            public string Name { get; set; }
            public List<ImageDTO> Images { get; set; }
        }

        public class ImageDTO
        {
            public Guid Id { get; set; }
            public string Name { get; set; }
            public string Extension { get; set; }
            public DateTime Created { get; set; }
        }
    }
}

Foundant.ImageStore.Web/Pages/Album/Index.cshtml
@page "{id:Guid}"
@model Foundant.ImageStore.Web.Pages.Album.IndexModel
@{
    ViewData["Title"] = "Image Management";
}

<div style="display: flex; flex-direction: row; margin-left: auto; margin-right: auto; margin-top: 2rem;">
    <div style="display: flex; width: 50%; justify-content: center">
        <form method="post" enctype="multipart/form-data">
            <div style="display: flex; flex-direction: column">
                <input asp-for="Data.AlbumId" type="hidden" />
                <div class="formGroup">
                    <div style="width: 20%">
                        <label asp-for="Data.ImageName" class="formGroupLabel">Image Name:</label>
                    </div>
                    <div style="width: 80%">
                        <input asp-for="Data.ImageName" type="text" placeholder="Enter an Image Name" class="formGroupField" />
                    </div>
                </div>
                <div class="formGroup">
                    <div style="width: 20%">
                        <label asp-for="Data.File" class="formGroupLabel">Image:</label>
                    </div>
                    <div style="width: 80%">
                        <input asp-for="Data.File" type="file" placeholder="Upload an Image" class="formGroupField" />
                    </div>
                </div>
                <div class="formGroup">
                    <div style="width: 20%"></div>
                    <div style="width: 80%">
                        <button type="submit" class="formButton">Update</button>
                    </div>
                    </div>
                </div>
        </form>
    </div>
    <div style="display: flex; flex-direction: column; width: 50%; justify-content: center">
        <div>
            <form method="post" asp-page-handler="SearchByTag" style="width: 100%;">
                <input asp-for="AlbumId" type="hidden" />
                <div style="display: flex; align-items: center; border-bottom: 1px solid #808080; padding-top: .5rem; padding-bottom: .5rem;">
                    <select asp-for="TagToSearch" asp-items="@(new SelectList(Model.Tags))" class="formSelect">
                        <option value="">Pick one</option>
                    </select>
                    <button type="submit" class="formButton">Search by Tag</button>
                </div>
            </form>
        </div>
        <div style="display: flex; flex-direction: row">
            @if (Model.AlbumDetails.Images != null)
            {
                foreach (var image in Model.AlbumDetails.Images.OrderBy(c => c.Created))
                {
                    <div style="display: flex; flex-direction: column; align-items: center">
                        <a asp-page="/Image/Index" asp-route-albumId="@Model.AlbumDetails.Id" asp-route-imageId="@image.Id">
                            <img src="~/albums/@Model.AlbumDetails.Id/@image.Id@image.Extension" alt="@image.Name" />
                        </a>
                        <span>@image.Name</span>
                        <a asp-page="/Album/Index" asp-page-handler="DeleteImage" asp-route-albumId="@Model.AlbumDetails.Id" asp-route-imageId="@image.Id">Delete</a>
                    </div>
                }
            }
        </div>
    </div>
</div>